name: Dynatrace Endpoint Tester
description: |
  Automatically score your webpage health using Dynatrace. List endpoints as code and get health results in the PR.
runs:
  using: docker
  image: Dockerfile

branding:
  icon: arrow-right
  color: purple
